# Provide your custom dashboard url here if you self-host the dashboard. An empty string will default to the provided dashboard service
# NO TRAILING SLASHES!
# Example: https://example.com:4000
self-hosted-dashboard-url: ''

# Prefix for all slurp responses, example: "\u00A76[Slurp] "
slurp-prefix: "\u00A74[Slurp] \u00A7f"

# The multiplication ratio of shots to sips. Fractional shots will be converted to sips. Default: 20 (20 sips will be one shot)
shots-to-sips-multiplier: 20

# Enable drinking buddies
drinking-buddy-enabled: true
# Change the size of a buddy group (Default: 2 players)
drinking-buddy-group-size: 2
# Change the interval of choosing new drinking buddies in seconds. (Default: 900 (900 seconds = 15 minutes))
drinking-buddy-interval: 900

drinking-savezone:
  shots:
    min: 75
    max: 125
  sips:
    min: 75
    max: 125

drinking-events:
  block-break-events:
    coalore-chance: 0.07
    copperore-chance: 0.3
    diamond-chance: 1
    emerald-chance: 1
    enchientdebris-chance: 1
    gold-chance: 0.17
    iron-chance: 0.1
    lapis-chance: 0.17
    nethergold-chance: 0.15
    netherquartz-chance: 0.08
    redstone-chance: 0.07
    stone-chance: 0.002
  block-place-events:
    craftingtable-chance: 1
    planks-chance: 0.005
    torch-chance: 0.25


slurp-console-debug-info: false