api:
  url: "https://pocketbase-sg44w4c4w8wggkwwg0ww048g.dev.hedium.nl/"
  token: ""

google-ai:
  token: ""

chat:
  prefix: "§8[§6Slurp§8] §r"

game:
  # Ratio of shots to sips. A value of 10 means 1 shot for every 10 sips.
  sip-shot-ratio: 10

  # Time in seconds between each event generation.
  generation-interval: 300

  # Modifier for the chance of events to trigger. Higher values mean more events.
  difficulty-multiplier: 1

  minimal-rarity: 30
