api:
  url: "https://pocketbase-sg44w4c4w8wggkwwg0ww048g.dev.hedium.nl/"
  token: ""

chat:
  prefix: "§8[§6Slurp§8] §r"

game:
  sip-shot-ratio: 10

  # Modifier for the chance of events to trigger. Higher values mean more events.
  difficulty-multiplier: 1

game-events:
  furnace-burn:
    enabled: true
    chance: 4096
    consumables:
    - type: SHOT
      message: "§e%player% burned their hand on the furnace! They take a shot!"
      amount: 1
      target: PLAYER
      giveable: false
  lucy-stone:
    enabled: true
    chance: 8192
    consumables:
    - type: SHOT
      message: "§e%player% just found a §6lucystone! §eEveryone takes a shot!"
      amount: 1
      target: ALL
      giveable: false
  choking-player:
    enabled: true
    chance: 64
    consumables:
    - type: SIP
      message: "§e%player% choked on their food! They take 5 sips!"
      amount: 5
      target: PLAYER
      giveable: false
  broken-legs:
    enabled: true
    chance: 32
    consumables:
    - type: SIP
      message: "§e%player% broke their legs! They take 5 sips!"
      amount: 5
      target: PLAYER
      giveable: false
  player-death:
    enabled: true
    chance: 1
    consumables:
    - type: SHOT
      message: "§e%player% died! They take a shot!"
      amount: 1
      target: PLAYER
      giveable: false
  player-kill:
    enabled: true
    chance: 1
    consumables:
    - type: SHOT
      message: "§e%player% killed someone! They take a shot!"
      amount: 1
      target: PLAYER
      giveable: false
  iron-ore:
    enabled: true
    chance: 16
    consumables:
    - type: SIP
      message: "§e%player% found some iron ore! They can give out 5 sips!"
      amount: 5
      target: PLAYER
      giveable: true
  gold-ore:
    enabled: true
    chance: 8
    consumables:
    - type: SIP
      message: "§e%player% found some gold ore! They can give out 5 sips!"
      amount: 5
      target: PLAYER
      giveable: true
  diamond-ore:
    enabled: true
    chance: 4
    consumables:
    - type: SHOT
      message: "§e%player% found some diamond ore! A random player takes a shot!"
      amount: 1
      target: RANDOM
      giveable: false
  lapis-ore:
    enabled: true
    chance: 16
    consumables:
    - type: SIP
      message: "§e%player% found some lapis ore! Everyone takes 5 sips!"
      amount: 5
      target: ALL
      giveable: false
  emerald-ore:
    enabled: true
    chance: 2
    consumables:
    - type: SHOT
      message: "§e%player% found some emerald ore! %target% takes 5 sips!"
      amount: 1
      target: RANDOM
      giveable: false
  redstone-ore:
    enabled: true
    chance: 16
    consumables:
    - type: SIP
      message: "§e%player% found some redstone ore! They give out 8 sips!"
      amount: 8
      target: PLAYER
      giveable: true
  coal-ore:
    enabled: true
    chance: 24
    consumables:
    - type: SIP
      message: "§e%player% found some coal ore! They give out 5 sips!"
      amount: 5
      target: PLAYER
      giveable: true
  quartz-ore:
    enabled: true
    chance: 32
    consumables:
    - type: SIP
      message: "§e%player% found some quartz ore! They give out 8 sips!"
      amount: 8
      target: PLAYER
      giveable: true
  netherite-ore:
    enabled: true
    chance: 2
    consumables:
    - type: SHOT
      message: "§e%player% found some netherite ore! They give out 1 shot!"
      amount: 1
      target: PLAYER
      giveable: true
  hostile-mob-kill:
    enabled: true
    chance: 16
    consumables:
    - type: SIP
      message: "§e%player% killed a hostile mob! They give out 5 sips!"
      amount: 5
      target: PLAYER
      giveable: true
  passive-mob-kill:
    enabled: true
    chance: 16
    consumables:
    - type: SIP
      message: "§e%player% killed a passive mob! They take 5 sips!"
      amount: 5
      target: PLAYER
      giveable: false
  logs:
    enabled: true
    chance: 64
    consumables:
    - type: SIP
      message: "§e%player% found some logs! They give out 2 sips!"
      amount: 2
      target: PLAYER
      giveable: true
  torch:
    enabled: true
    chance: 64
    consumables:
    - type: SIP
      message: "§e%player% placed a torch! They take a sip!"
      amount: 1
      target: PLAYER
      giveable: false
