api:
  url: "https://pocketbase-sg44w4c4w8wggkwwg0ww048g.dev.hedium.nl/"
  username: "slurp"
  password: "slurp"

google-ai:
  token: ""
  additional-instructions: ""

chat:
  prefix: "§8[§6Slurp§8] §r"

game:
  # Ratio of shots to sips. A value of 10 means 1 shot for every 10 sips.
  sip-shot-ratio: 10

  # Time in seconds between each event generation.
  generation-interval: 300

  # Modifier for the chance of events to trigger. Higher values mean more events.
  difficulty-multiplier: 1

  # Minimum rarity for an event to be considered.
  minimal-rarity: 30

  # Minimal rarity for event to play a sound.
  sound-rarity: 80
