# Provide your custom dashboard url here if you self-host the dashboard. An empty string will default to the provided dashboard service
# NO TRAILING SLASHES!
# Example: https://example.com:4000
self-hosted-dashboard-url: ''

# Prefix for all slurp responses, example: '[Slurp] '
slurp-prefix: '[Slurp] '

# The multiplication ratio of shots to sips. Fractional shots will be converted to sips. Default: 20 (20 sips will be one shot)
shots-to-sips-multiplier: 20

# Enable drinking buddies
drinking-buddy-enabled: true
# Change the size of a buddy group (Default: 2 players)
drinking-buddy-group-size: 2
# Change the interval of choosing new drinking buddies in seconds. (Default: 900 (900 seconds = 15 minutes))
drinking-buddy-interval: 900

slurp-console-debug-info: false